### ISSUE TITLE
How to read grammar definitions?

### ISSUE THREAD

**Issue by bendtherules** [TimothyGu/es-howto#12]
Syntax or grammar of the language, looks like this -

![Screenshot 2020-04-16 at 9 15 00 PM](https://user-images.githubusercontent.com/3101150/79477158-7d26dc00-8027-11ea-919b-4e2f1b32620a.png)

But how to understand this definitions correctly? 
Is this another intermediate language which defines the formal language? What is it called? How to understand it?

If you could explain a little bit, that would be very helpful.

I read little about Web IDL, but it doesn't look like that.

**Comment by TimothyGu** [comment]
The meta-language for defining the grammar is similar to what's known as [Backus–Naur Form](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form), or BNF, but it is formally covered by this section: https://tc39.es/ecma262/#sec-syntactic-and-lexical-grammars. You could understand it better by reading through these two links, but generally a university course on programming languages would be even better, like these lecture slides from MIT's OpenCourseWare: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-035-computer-language-engineering-spring-2010/lecture-notes/MIT6_035S10_lec02.pdf.

This has nothing to do with Web IDL, a much simpler language than JavaScript, even though its spec borrows ES spec's notations.

**Comment by bendtherules** [comment]
@TimothyGu Thanks, that was super helpful in pointing me towards the right direction.

I couldn't understand the meaning of subscripted annotations like +,? earlier, but it is much more clear now after reading that section.

Overall, from what i understand - the spec uses a modified version of BNF grammar and the modifications are described in that section.

**Comment by bendtherules** [comment]
Also, do you think it makes sense - to add a summary of how to read the grammar notation?

Specially, with the annotations, it can look quite confusing at first. And it's not immediately obvious where to look for its meaning. 

(Even though you summarised the sections at start of the page, readers might not think it's important to read the notational conventions at start)

**Comment by hax** [comment]
Spec has a section to explain the grammar: https://tc39.es/ecma262/#sec-syntactic-and-lexical-grammars , I'm not sure how can we write a more simple and friendly explanation. (But I find the README of https://github.com/rbuckton/grammarkdown may be also helpful.)
