### ISSUE TITLE
https://timothygu.me/es-howto is down

### ISSUE THREAD

**Issue by yjaaidi** [TimothyGu/es-howto#15]
Hi Timothy, apparently https://timothygu.me/es-howto is down due to a certificate issue.
Thank you for the great job 😊

**Comment by rdazvd** [comment]
Cloudflare's Always Online feature is serving me the latest version cached on the Internet Archive's Wayback Machine (dated last January 8th as of this writing). It's [here](https://web.archive.org/web/20210108172241/https://timothygu.me/es-howto/) for those of us who conveniently need it.

**Comment by TimothyGu** [comment]
It looks like there was something strange going on with GitHub Pages–Cloudflare interop. Should be fixed now.

Sorry about the trouble.
